### ISSUE TITLE
Form Data Validation

### ISSUE THREAD

**Issue by msrd0** [msrd0/gotham_formdata#1]
Could look something like proposed here: https://github.com/gotham-rs/gotham/issues/11#issuecomment-373565350

## Progress

 - [x] Implement initial validation (#2)
 - [x] Implement some common validators
   - [x] `min_length`, `max_length` for string types (#5)
   - [x] `min`, `max` for integer types (#6)
   - [x] `regex` for string types (#8)
   - [x] ~`uppercase_only`, `lowercase_only`, `trimmed` and similar for string types~ can be done with `regex`
   - [x] `expected` for all types that implement `PartialEq` (#9)
 - [x] Allow specifying custom error messages (#11)
 - [x] Allow multiple validators to be combined (#12)
